import 'dart:io';

import 'package:collection/collection.dart';

import 'shared.dart';

/// --- Day 22: Monkey Market ---
///
/// Determine the numbers generated by monkeys at an auction.
/// Each monkey starts with a secret number, and generates their
/// next number based on a defined set of operations.
///
/// Return the sum of all secret numbers after 2000 iterations.
Future<int> calculate(File file) async {
  final data = await loadData(file);

  return data.map((s) => _simulate(s, 2000)).sum;
}

/// Generate the secret number after [iterations], starting at
/// the given [starting] secret number.
int _simulate(int starting, int iterations) {
  int secret = starting;
  for (int i = 0; i < iterations; i++) {
    secret = nextSecret(secret);
  }
  return secret;
}
